In [2]:
import numpy as np
#Calculate mean, median, standard deviation and variance of 1D array
array=np.array([10,20,30,40,50,100])
mean=np.mean(array)
median=np.median(array)
std_dev=np.std(array)
variance=np.var(array)
print(mean,median,std_dev,variance)

41.666666666666664 35.0 29.1070819942883 847.2222222222222


In [3]:
#Logical operation
array=np.array([10,20,30,40,50,100,500])
#Return array with elements greater than 70
result=array[array>70]
print(result)

[100 500]


In [4]:
matrix=np.random.random((3,3))
print(matrix)

[[0.82121513 0.49203594 0.4151147 ]
 [0.81256756 0.08026887 0.34758784]
 [0.39005618 0.57817462 0.96426008]]


In [7]:
#Create an array of 10 random integers between 50 and 100
random_int_matrix=np.random.randint(50,100,9).reshape(3,3)
print(random_int_matrix)
#Multiply matrix by 10
result=random_int_matrix*10
print(result)

[[66 67 76]
 [92 77 63]
 [51 91 65]]
[[660 670 760]
 [920 770 630]
 [510 910 650]]


In [11]:
#Create an array with some missing values(Nans) and calculate the mean ignoring Nans
array_with_missing_values=np.array([10,20,np.nan,50,70,np.nan])
print(array_with_missing_values)
mean=np.nanmean(array_with_missing_values)
print(mean)

[10. 20. nan 50. 70. nan]
37.5


In [16]:
#Apply the sine function to each element in an array
#[0,pi/2,pi,3*pi/2,2*pi]
sine_array=[0,np.pi/2,np.pi,3*np.pi/2,2*np.pi]
sine_values=np.sin(sine_array)
print(sine_values)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


In [15]:
#Find the unique elements in an array
repeated_values=np.array([1,1,1,10,3,3,3,5,5,66,88,9,19,20,34])
unique_values=np.unique(repeated_values)
print(unique_values)

[ 1  3  5  9 10 19 20 34 66 88]


In [17]:
#Sorting the array in ascending order
unsorted_array=np.array([100,200,50,10,2,5,500,1000,350,1])
sorted_array=np.sort(unsorted_array)
print(sorted_array)

[   1    2    5   10   50  100  200  350  500 1000]


In [22]:
#Find the shape, size and the number of dimension in an array
array_1d=np.array([1])
array_2d=np.random.random([2,3])
array_3d=np.random.random([4,9,7])
shape_1d=array_1d.shape
shape_2d=array_2d.shape
shape_3d=array_3d.shape
size_1d=array_1d.size
size_2d=array_2d.size
size_3d=array_3d.size
dimension_1d=array_1d.ndim
dimension_2d=array_2d.ndim
dimension_3d=array_3d.ndim
print(shape_1d,shape_2d,shape_3d)

(1,) (2, 3) (4, 9, 7)


In [10]:
#Webscraping
import requests
from bs4 import BeautifulSoup
def scrape_headings(url):
    #Send a GET request to the url
    response=requests.get(url)
    #Parse the html content using BeautifulSoup
    soup=BeautifulSoup(response.content,"html.parser")
    #Find all the headings elements
    headings=soup.find_all(["h1","h2","h3","h4","h5","h6"])
    #Print the text of each heading
    for heading in headings:
        print(heading.text.strip())

input_url=input("Enter the URL to scrape:")
scrape_headings(input_url)

Enter the URL to scrape: https://facebook.com


Connect with friends and the world around you on Facebook.
