In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#Create NumPy array
import numpy as np
array=np.array([5,10,15,20,25])
print(array)

[ 5 10 15 20 25]


In [5]:
#Array Operating
#Average of array
average=np.mean(array)
print(average)

15.0


In [7]:
#Multidimensional array
height_cm=np.array([[170,175,180],[185,190,195],[200,205,210]])
print(height_cm)

[[170 175 180]
 [185 190 195]
 [200 205 210]]


In [9]:
#Array indexing
first_height=height_cm[0]
print(first_height)
second_height_2=height_cm[1][1]
print(second_height_2)

[170 175 180]
190


In [12]:
#Convert temperature from °C to °F
temperature=np.array([[20,25,30],[35,40,45],[90,95,100]])
f=(temperature*9/5)+32
print(f)
k=temperature+273.15
print(k)

[[ 68.  77.  86.]
 [ 95. 104. 113.]
 [194. 203. 212.]]
[[293.15 298.15 303.15]
 [308.15 313.15 318.15]
 [363.15 368.15 373.15]]


In [15]:
#Linear algebra
sales=np.array([[100,200,300],[400,500,600]])
quantity=np.array([[10,20,30],[40,50,60]])
revenue=np.dot(sales,quantity.T)
print(revenue)

[[14000 32000]
 [32000 77000]]


In [21]:
#Zeros and ones in matrix
print("Zeros matrix 3x3 is:\n",np.zeros((3,3),dtype=int))
print("Ones matrix 3x3 is:\n",np.ones((3,3),dtype=int))
print("Eye matrix 5x5 is:\n",np.eye(5,dtype=int))

Zeros matrix 3x3 is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Ones matrix 3x3 is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Eye matrix 5x5 is:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [24]:
#Create 1D NumPy array values ranging from 0 to 9
array_1D=np.arange(10)
print(array_1D)

#Create 2D NumPy array with the shape (3,3) containing values from 1 to 9
array_2D=np.arange(1,10).reshape(3,3)
print(array_2D)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Perform element-wise addition, subtraction, multiplication and division in 1D array[1,2,3]
array1=np.array([1,2,3])
array2=np.array([4,5,6])
addition=array1+array2
subtraction=array2-array1
multiplication=array1*array2
division=array2/array1
print(addition, subtraction,multiplication,division)

[5 7 9] [3 3 3] [ 4 10 18] [4.  2.5 2. ]
